### ISSUE TITLE
Feature Request - Have the version too in the workflow file

### ISSUE THREAD

**Issue by vikas027** [sethvargo/ratchet#1]
Thanks for creating this @sethvargo.

I think it will be good to have the version too alongside the hash, something like below to easily know what version we are using.

```yaml
uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b' #v 3.0
# or
image: 'ubuntu@sha256:47f14534bda344d9fe6ffd6effb95eefe579f4be0d508b7445cf77f61a0e5724' #tag 20.04
```
