### ISSUE TITLE
Minimize yaml changes to only the essential

### ISSUE THREAD

**Issue by cwilper** [sethvargo/ratchet#117]
### New issue?

- [x] I have reviewed the [Known Issues](https://github.com/sethvargo/ratchet#known-issues) and confirm this is not a known issue.

### TL;DR

I would like ratchet to only update the minimal necessary lines in my yaml config files. This would make the output easier to review (and thus trust and approve), and allow teams to manage CI/CD config file linting as a separate concern -- their preferred rules might differ from the output of ratchet.

### Detailed design

It seems the yaml parsing library is doing some opinionated normalization by the time the output is written. If there's a way to tell it to avoid that and only write effective changes, that would be ideal.

Failing that, a more brute-force approach would be to post-process the current output as text, and for each line ending with a `# ratchet:` comment, apply that (if needed) to a second pass of the input file line by line. There are probably some corner cases to watch out for with this approach, though.

### Additional information

Here's an example input with expected output vs. actual. 

> [!Note]
> The last line of the multi-line script at the end has a _trailing whitespace_ in order
> to provoke one particular kind of unexpected re-formatting teams might see.
>
> Other reformattings can include indentation (discussed elsewhere as a KI)
> as well as spaces within brackets, but there are several others NOT demonstrated
> here that teams may have their own conflicting linting rules for.

```yaml
name: Example Workflow

on: push

jobs:
  run-script:
    runs-on: [ ubuntu ]
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Run multi-line Bash script
        run: |
          echo "Gonna print the date"
          date 
```

Expected diff:

```diff
11c11
<         uses: hashicorp/setup-terraform@v2
---
>         uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # ratchet:hashicorp/setup-terraform@v2
```

Actual diff:

```diff
8c8
<     runs-on: [ ubuntu ]
---
>     runs-on: [ubuntu]
11c11
<         uses: hashicorp/setup-terraform@v2
---
>         uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # ratchet:hashicorp/setup-terraform@v2
13,15c13,15
<         run: |
<           echo "Gonna print the date"
<           date
---
>         run: "echo \"Gonna print the date\"\ndate \n"
>
>
```

Sample `.yamllint.yaml` file:

```yaml
extends: default
rules:
  brackets:
    min-spaces-inside: 1
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0
  indentation: disable
  line-length:
    max: 80
  quoted-strings:
    quote-type: single
    required: false
    allow-quoted-quotes: false
  trailing-spaces: disable
  truthy:
    check-keys: false
```

For this linting config, the input and expected diff do not violate any of the rules, but the actual output does:

```
> yamllint output-actual.yaml

output-actual.yaml
  8:15      error    too few spaces inside brackets  (brackets)
  8:21      error    too few spaces inside brackets  (brackets)
  11:81     error    line too long (119 > 80 characters)  (line-length)
  13:14     error    string value is not quoted with single quotes  (quoted-strings)
  15:1      error    too many blank lines (2 > 0)  (empty-lines)
```
