### ISSUE TITLE
Using ratchet container in GitHub Actions container workflow

### ISSUE THREAD

**Issue by ScottGuymer** [sethvargo/ratchet#15]
### TL;DR

Currently unable to use the container in a GH Actions container workflow due to missing dependencies.

Using something similar to this in a workflow.

```yaml
name: Ratchet

on:
  push:
    branches:
      - 'dependabot/github_actions/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/sethvargo/ratchet:0.2.0
    name: ratchet
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
      - run: /ratchet pin ./.github/workflows/test.yml
      - run: cat ./.github/workflows/test.yml
      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
```

The workflow fails with

```
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "tail": executable file not found in $PATH: unknown
```

The command that GH runs is

```
  /usr/bin/docker create --name e2aa5e69c559473fbfee20eb938ecedb_ghcriosethvargoratchet020_164211 --label 08450d --workdir /__w/dependabot-test/dependabot-test --network github_network_0d6c4b639fee4544bb9ce8c96c4be9a2  -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work":"/__w" -v "/home/runner/runners/2.291.1/externals":"/__e":ro -v "/home/runner/work/_temp":"/__w/_temp" -v "/home/runner/work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" ghcr.io/sethvargo/ratchet:0.2.0 "-f" "/dev/null"
```

**Comment by sethvargo** [comment]
Hi @ScottGuymer 

The ratchet container is a SCRATCH container with only the most minimal set of things needed to run ratchet as a CLI. It does not contain an operating system or any packages. As such, I would not recommend using it as the base container for actions. I do have plans to make an official GitHub Action for ratchet, but in the meantime, you should be able to use the container in a _step_:

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    name: ratchet
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0

      - uses: docker://ghcr.io/sethvargo/ratchet:0.2.0
        with:
          args: ['pin', './.github/workflows/test.yml']

      - run: cat ./.github/workflows/test.yml

      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
```

Let me know if you have any questions.
