### ISSUE TITLE
exclude not working

### ISSUE THREAD

**Issue by davidkarlsen** [sethvargo/ratchet#16]
### TL;DR
```yaml
uses: 'github/codeql-action/analyze@v2' # ratchet:exclude
```
becomes:
```yaml
       - name: Initialize CodeQL
         if: github.ref != 'refs/heads/master'
-        uses: 'github/codeql-action/init@v2' # ratchet:exclude
+        uses: 'exclude'
```
when running

` ratchet update build.yaml `

### Expected behavior

should preserve existing config

### Observed behavior

becomes invalid

### Version

0.2.0

### On what operating system are you using ratchet?

Mac OS

### CI/CD workflow file

```yaml
N/A
```

### Relevant log output

```text
N/A
```

### Additional information

N/A
