### ISSUE TITLE
check: support directory scan

### ISSUE THREAD

**Issue by Dentrax** [sethvargo/ratchet#28]
### TL;DR

It would be nice to support directory inputs for `check` subcommand:

```
$ ratchet check .github/workflows/
failed to parse .github/workflows/: failed to decode yaml: yaml: input error: read .github/workflows/: is a directory
```

### Detailed design

```markdown
If given arg is directory, traverse all `.yml | .yaml` files (it's ok to ignore symlinks for now).

If given arg is file, it should work as is.
```

Example output format:
```
[PASS] .github/workflows/foo.yaml
[FAIL] .github/workflows/bar.yaml
[PASS] .github/workflows/baz.yaml
```

**Comment by sethvargo** [comment]
Hi @Dentrax 

This gets really complex with authentication, so I would prefer not to support a collection of files. Instead, you can use unix commands like `find` an `xargs` to accomplish this:

```sh
find . -name '*.yml' -exec ratchet check {} \;
```

**Comment by Dentrax** [comment]
Yes, I've tried the same method to scan directory but if we want to implement this in the CI, things get complicated since our entry point is `ratchet` in Docker image. So I want to use the following use-case scenario. Notice that we can not use the way you provided above.

```
# Example of checking all versions under .github/workflows/ are pinned.
      - uses: 'docker://ghcr.io/sethvargo/ratchet:0.2.3'
        with:
          args: 'check .github/workflows/'
```

We created a simple PR anyway 🤷‍♂️ #29 (@developer-guy)
