### ISSUE TITLE
Blank lines in YAML files are removed and single quotes replaced by double quotes

### ISSUE THREAD

**Issue by fdc-viktor-luft** [sethvargo/ratchet#35]
### TL;DR

Running e.g. the "pin" command does some unwanted reformatting of the YAML files.

### Expected behavior

Keeping the preferred styles and just updating the one line containing the unpinned versions.

### Observed behavior

Running the "pin" command for instance on parts that look like this

```yaml
  ui-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ui-tests
        name: 'Run UI Tests'
        with:
          gitCryptKey: ${{ secrets.GIT_CRYPT_KEY }}

  system-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/system-tests
        name: 'Run System Tests'
        with:
          gitCryptKey: ${{ secrets.GIT_CRYPT_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

Become this:

```yaml
  ui-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - uses: ./.github/actions/ui-tests
        name: "Run UI Tests"
        with:
          gitCryptKey: ${{ secrets.GIT_CRYPT_KEY }}
  system-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - uses: ./.github/actions/system-tests
        name: "Run System Tests"
        with:
          gitCryptKey: ${{ secrets.GIT_CRYPT_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```

### Version

0.3.0

### On what operating system are you using ratchet?

Linux

### CI/CD workflow file

```yaml
ui-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ui-tests
        name: 'Run UI Tests'
        with:
          gitCryptKey: ${{ secrets.GIT_CRYPT_KEY }}

  system-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/system-tests
        name: 'Run System Tests'
        with:
          gitCryptKey: ${{ secrets.GIT_CRYPT_KEY }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```
