### ISSUE TITLE
Allow filtering of certain docker images by URL

### ISSUE THREAD

**Issue by fdc-viktor-luft** [sethvargo/ratchet#36]
### TL;DR

Currently running e.g. the "pin" command tries to pin every image and action. For private images this is not wanted and currently lets the execution fail. So I have to manually out-comment the line before running the command.

### Detailed design

```markdown
container:
      image: eu.gcr.io/<GCP_ID>/images/<IMAGE_NAME>:<IMAGE_TAG>
      credentials:
        username: _json_key
        password: ${{ secrets.GCP_SERVICE_ACCOUNT }}
```

### Additional information

- Option 1: Allow to ignore certain domains like `eu.gcr.io/<GCP_ID>` as Ratchet would run into authorization errors.
- Option 2: Print a warning, but allow to proceed anyway, instead of doing no modifications to the file

**Comment by sethvargo** [comment]
You can exclude specific lines with a `ratchet:exclude` comment: https://github.com/sethvargo/ratchet#excluding. In your case, that would be:

```yaml
container:
  image: eu.gcr.io/<GCP_ID>/images/<IMAGE_NAME>:<IMAGE_TAG> # ratchet:exclude
  credentials:
    username: _json_key
    password: ${{ secrets.GCP_SERVICE_ACCOUNT }}
```

Additionally, for private images, Ratchet uses the default Docker keychain auth. So if the authenticated user has permission to read images from the Docker registry, so will ratchet: https://github.com/sethvargo/ratchet#auth
