### ISSUE TITLE
Pinning does not work for composite GitHub Actions

### ISSUE THREAD

**Issue by fdc-viktor-luft** [sethvargo/ratchet#37]
### TL;DR

Composite actions allow you to extract common functionality into other YAML files. However, Ratchet does nothing except for unwanted formatting on them.

### Expected behavior

I would have expected that version pinning also works on this kind of file.

### Observed behavior

In the below example the line including `actions/setup-go@v3` was not updated.

### Version

0.3.0

### On what operating system are you using ratchet?

Linux

### CI/CD workflow file

```yaml
name: "Go Install"
description: "Install dependencies with go"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        cache: true
        cache-dependency-path: "go.sum"
        go-version: "1.18"
    - name: "Install required modules"
      shell: bash
      run: |
        go install github.com/golang/protobuf/protoc-gen-go
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
```
