### ISSUE TITLE
Cannot handle matrix jobs based on docker

### ISSUE THREAD

**Issue by npalm** [sethvargo/ratchet#7]
Great initiative, looking already a long time for a good way to fix version and not lock on un-controlled tags.

Just tried ratchet on my project (https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/.github/workflows/ci.yml). In the build file I use a matrix job to check against different docker conatiners.

```yml
jobs:
  verify_module:
    strategy:
      matrix:
        terraform: [1.1.9]
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
    steps:
      - uses: actions/checkout@v3
      - run: terraform init -get -backend=false -input=false
      - run: terraform fmt -recursive -check=true -write=false
```

When running ratchet it throws the following error:

```
failed to pin refs: 1 error occurred:
	* failed to resolve "container://hashicorp/terraform:${{ matrix.terraform }}": failed to parse Container ref: could not parse reference: hashicorp/terraform:${{ matrix.terraform }}
```

Once adding ignore comments to the line specify the container it works like a charm. Would be great when you can support the matrix construction as well. Or in the meantime generate warning message instead of an error.

**Comment by sethvargo** [comment]
Hi @npalm 

Unfortunately there's no easy way to support the matrix construction, since that's not pure YAML. GitHub's `${{}}` syntax is a special pre-processing that happens. For example, the following would be impossible to resolve:

```yaml
image: hashicorp/terraform:${{ env.TERRAFORM_VERSION }}
```

In this case, we _might_ know the matrix in advance (as in your example), but it's also possible that we don't:

```yaml
jobs:
  verify_module:
    strategy:
      matrix:
        terraform: 
        - ${{ env.TERRAFORM_VERSION }}
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:${{ matrix.terraform }}
```

I'll need to add this to the [list of known limitations](https://github.com/sethvargo/ratchet#known-issues).
